import 'dart:convert';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:openchat/crypto/kt_log_verify.dart';

/// Cross-language vectors: every hash below was GENERATED BY the Go
/// implementation (backend/internal/ktlog) over leaves "EV0".."EV4". If the
/// Dart verifier drifts from the Go prover, these fail — that's the point.
void main() {
  final root5 = KtLogVerify.hexToBytes(
    '6408dc8f562b392d389c510f86c463d140c6eca63fe72e1ebf2ee05699ccb81a',
  );
  final root3 = KtLogVerify.hexToBytes(
    'bf0e138913d25046bf7d20a43f507769f3bedf7dde1d8122aabdeef8eacc6064',
  );
  final leaf2 = KtLogVerify.hexToBytes(
    'b36d1ac35833a6fab64633c87b67ea7fb0997027ea470f09111f02528444663a',
  );
  final inclusion2 = [
    '542e57cfd7300043ceb5dd13db7191fc5cd48d0c529e751e5ba1682a03ae766a',
    'c06cbda202971c9caff6e9f159f59bd49b3bf5981e4354349a4adfaf28a68702',
    '11e67ce9329c3435092edd81b7848f7769c94f0db0a5a8b7024b55c89b0b8e5a',
  ].map(KtLogVerify.hexToBytes).toList();
  final consistency3to5 = [
    'b36d1ac35833a6fab64633c87b67ea7fb0997027ea470f09111f02528444663a',
    '542e57cfd7300043ceb5dd13db7191fc5cd48d0c529e751e5ba1682a03ae766a',
    'c06cbda202971c9caff6e9f159f59bd49b3bf5981e4354349a4adfaf28a68702',
    '11e67ce9329c3435092edd81b7848f7769c94f0db0a5a8b7024b55c89b0b8e5a',
  ].map(KtLogVerify.hexToBytes).toList();

  test('leaf hashing matches the Go implementation', () {
    expect(KtLogVerify.leafHash(utf8.encode('EV2')), equals(leaf2));
  });

  test('Go-generated inclusion proof verifies (leaf 2 of 5)', () {
    expect(
      KtLogVerify.verifyInclusion(
        leaf: leaf2,
        index: 2,
        treeSize: 5,
        proof: inclusion2,
        root: root5,
      ),
      isTrue,
    );
  });

  test('inclusion rejects wrong leaf, index, and truncated proofs', () {
    expect(
      KtLogVerify.verifyInclusion(
        leaf: KtLogVerify.leafHash(utf8.encode('EVIL')),
        index: 2,
        treeSize: 5,
        proof: inclusion2,
        root: root5,
      ),
      isFalse,
    );
    expect(
      KtLogVerify.verifyInclusion(
        leaf: leaf2,
        index: 3,
        treeSize: 5,
        proof: inclusion2,
        root: root5,
      ),
      isFalse,
    );
    expect(
      KtLogVerify.verifyInclusion(
        leaf: leaf2,
        index: 2,
        treeSize: 5,
        proof: inclusion2.sublist(0, 2),
        root: root5,
      ),
      isFalse,
    );
  });

  test('Go-generated consistency proof verifies (3 → 5)', () {
    expect(
      KtLogVerify.verifyConsistency(
        m: 3,
        n: 5,
        oldRoot: root3,
        newRoot: root5,
        proof: consistency3to5,
      ),
      isTrue,
    );
  });

  test('consistency rejects a different old root (split view)', () {
    expect(
      KtLogVerify.verifyConsistency(
        m: 3,
        n: 5,
        oldRoot: leaf2, // any wrong root
        newRoot: root5,
        proof: consistency3to5,
      ),
      isFalse,
    );
  });

  test('equal sizes need identical roots and an empty proof', () {
    expect(
      KtLogVerify.verifyConsistency(
        m: 5,
        n: 5,
        oldRoot: root5,
        newRoot: root5,
        proof: const [],
      ),
      isTrue,
    );
    expect(
      KtLogVerify.verifyConsistency(
        m: 5,
        n: 5,
        oldRoot: root3,
        newRoot: root5,
        proof: const [],
      ),
      isFalse,
      reason: 'same size, different roots = the equivocation signal',
    );
  });

  test('STH signatures round-trip with the canonical signed data', () async {
    final keyPair = await Ed25519().newKeyPair();
    final publicKey = await keyPair.extractPublicKey();
    const treeSize = 5;
    const rootHex =
        '6408dc8f562b392d389c510f86c463d140c6eca63fe72e1ebf2ee05699ccb81a';
    final signature = await Ed25519().sign(
      KtLogVerify.sthSignedData(treeSize, rootHex),
      keyPair: keyPair,
    );

    expect(
      await KtLogVerify.verifySthSignature(
        publicKeyB64: base64Encode(publicKey.bytes),
        treeSize: treeSize,
        rootHashHex: rootHex,
        signatureB64: base64Encode(signature.bytes),
      ),
      isTrue,
    );
    expect(
      await KtLogVerify.verifySthSignature(
        publicKeyB64: base64Encode(publicKey.bytes),
        treeSize: treeSize + 1, // tampered size
        rootHashHex: rootHex,
        signatureB64: base64Encode(signature.bytes),
      ),
      isFalse,
    );
  });

  test('hexToBytes round-trips', () {
    final bytes = KtLogVerify.hexToBytes('00ff10ab');
    expect(bytes, equals(Uint8List.fromList([0, 255, 16, 171])));
  });
}
