import 'dart:convert';
import 'dart:typed_data';

import 'package:crypto/crypto.dart' as crypto;
import 'package:cryptography/cryptography.dart';

/// Client-side verification for the server's key-transparency Merkle log
/// (RFC 6962/9162). Mirrors backend/internal/ktlog — the Dart test suite pins
/// vectors GENERATED BY the Go implementation, so the two can never drift
/// silently.
///
/// What this buys: the per-user KT chains prove one history is internally
/// consistent; these proofs + signed-head comparison prove the server shows
/// EVERYONE the same history. Two valid signed heads of equal size with
/// different roots are cryptographic evidence of equivocation.
class KtLogVerify {
  KtLogVerify._();

  /// Domain-separated leaf hash: SHA-256(0x00 || payload).
  static Uint8List leafHash(List<int> payload) {
    return Uint8List.fromList(
      crypto.sha256.convert([0x00, ...payload]).bytes,
    );
  }

  static Uint8List _nodeHash(List<int> left, List<int> right) {
    return Uint8List.fromList(
      crypto.sha256.convert([0x01, ...left, ...right]).bytes,
    );
  }

  static bool _bytesEqual(List<int> a, List<int> b) {
    if (a.length != b.length) return false;
    var diff = 0;
    for (var i = 0; i < a.length; i++) {
      diff |= a[i] ^ b[i];
    }
    return diff == 0;
  }

  /// RFC 9162 §2.1.3.2 inclusion verification.
  static bool verifyInclusion({
    required Uint8List leaf,
    required int index,
    required int treeSize,
    required List<Uint8List> proof,
    required Uint8List root,
  }) {
    if (index < 0 || treeSize <= 0 || index >= treeSize) return false;
    var fn = index;
    var sn = treeSize - 1;
    var r = leaf;
    for (final p in proof) {
      if (sn == 0) return false;
      if (fn.isOdd || fn == sn) {
        r = _nodeHash(p, r);
        // Collapse along the right edge; the unconditional shift below still
        // applies afterwards (the subtle off-by-one in this algorithm).
        while (fn.isEven && fn != 0) {
          fn >>= 1;
          sn >>= 1;
        }
      } else {
        r = _nodeHash(r, p);
      }
      fn >>= 1;
      sn >>= 1;
    }
    return sn == 0 && _bytesEqual(r, root);
  }

  /// RFC 9162 §2.1.4.2 consistency verification (old size [m] → new size [n]).
  static bool verifyConsistency({
    required int m,
    required int n,
    required Uint8List oldRoot,
    required Uint8List newRoot,
    required List<Uint8List> proof,
  }) {
    if (m < 0 || n < 0 || m > n) return false;
    if (m == n) return proof.isEmpty && _bytesEqual(oldRoot, newRoot);
    if (m == 0) return proof.isEmpty;
    var fn = m - 1;
    var sn = n - 1;
    while (fn.isOdd) {
      fn >>= 1;
      sn >>= 1;
    }
    Uint8List fr;
    Uint8List sr;
    List<Uint8List> rest;
    if (fn == 0) {
      fr = oldRoot;
      sr = oldRoot;
      rest = proof;
    } else {
      if (proof.isEmpty) return false;
      fr = proof.first;
      sr = proof.first;
      rest = proof.sublist(1);
    }
    for (final c in rest) {
      if (sn == 0) return false;
      if (fn.isOdd || fn == sn) {
        fr = _nodeHash(c, fr);
        sr = _nodeHash(c, sr);
        while (fn.isEven && fn != 0) {
          fn >>= 1;
          sn >>= 1;
        }
      } else {
        sr = _nodeHash(sr, c);
      }
      fn >>= 1;
      sn >>= 1;
    }
    return sn == 0 && _bytesEqual(fr, oldRoot) && _bytesEqual(sr, newRoot);
  }

  /// The canonical byte string the log's Ed25519 key signs — must match the
  /// backend's handlers.KTSthSignedData exactly.
  static List<int> sthSignedData(int treeSize, String rootHashHex) =>
      utf8.encode('openchat-kt-sth:v1:$treeSize:$rootHashHex');

  /// Verifies a signed tree head against the (pinned) log public key.
  static Future<bool> verifySthSignature({
    required String publicKeyB64,
    required int treeSize,
    required String rootHashHex,
    required String signatureB64,
  }) async {
    try {
      final publicKey = SimplePublicKey(
        base64Decode(publicKeyB64),
        type: KeyPairType.ed25519,
      );
      return await Ed25519().verify(
        sthSignedData(treeSize, rootHashHex),
        signature: Signature(base64Decode(signatureB64), publicKey: publicKey),
      );
    } catch (_) {
      return false;
    }
  }

  static Uint8List hexToBytes(String hexStr) {
    final out = Uint8List(hexStr.length ~/ 2);
    for (var i = 0; i < out.length; i++) {
      out[i] = int.parse(hexStr.substring(i * 2, i * 2 + 2), radix: 16);
    }
    return out;
  }
}
